cabal-version: 3.0
name:          compiler
version:       0.0.0.1
build-type:    Simple

executable compiler
  main-is:            main.hs
  hs-source-dirs:     app, src
  default-language:   Haskell2010
  default-extensions:
    NoImplicitPrelude
    OverloadedStrings
  other-modules:
    Quone.AST.Source
    Quone.Generate.R

  build-depends:
    , base         ^>=4.21.0.0
    , nri-prelude  ^>=0.6.1.2
